plugins {
	id 'java'
	id 'org.springframework.boot' version '3.3.5'
	id 'io.spring.dependency-management' version '1.1.6'
	id 'war'
}

group = 'com.pets.platform'
version = '0.0.1-SNAPSHOT'

java {
	toolchain {
		languageVersion = JavaLanguageVersion.of(17)
	}
}

repositories {
	mavenCentral()
}

dependencies {
	implementation 'org.springframework.boot:spring-boot-starter'
	testImplementation 'org.springframework.boot:spring-boot-starter-test'
	testRuntimeOnly 'org.junit.platform:junit-platform-launcher'
	implementation 'org.springframework.boot:spring-boot-starter-web'
	implementation 'org.springframework.boot:spring-boot-starter-tomcat'
	annotationProcessor 'org.springframework.boot:spring-boot-configuration-processor'
	implementation 'org.mybatis.spring.boot:mybatis-spring-boot-starter:3.0.3'
	implementation 'org.json:json:20200518'
    implementation 'org.apache.httpcomponents:httpclient:4.5.14'
    implementation 'org.apache.httpcomponents.client5:httpclient5'
        runtimeOnly 'mysql:mysql-connector-java:8.0.25'
    runtimeOnly 'org.postgresql:postgresql'
    implementation 'org.springframework.boot:spring-boot-starter-jdbc'
    implementation 'org.springframework.boot:spring-boot-starter-cache'
       implementation 'org.springframework.boot:spring-boot-starter-data-redis'
    //implementation 'org.springframework.boot:spring-boot-starter-data-redis-reactivre'
        implementation 'io.jsonwebtoken:jjwt-api:0.11.5'
    runtimeOnly 'io.jsonwebtoken:jjwt-impl:0.11.5'
    runtimeOnly 'io.jsonwebtoken:jjwt-jackson:0.11.5'
    implementation 'org.springframework.kafka:spring-kafka'
    implementation 'org.projectlombok:lombok'
	implementation 'org.springframework.boot:spring-boot-starter-data-mongodb'
	implementation group: 'org.springframework.boot', name: 'spring-boot-starter-security', version: '2.6.7'
	runtimeOnly 'com.h2database:h2'
	implementation group: 'org.springframework.boot', name: 'spring-boot-starter-validation', version: '2.5.4'
	implementation 'org.springframework.boot:spring-boot-starter-mail'
}

tasks.named('test') {
	useJUnitPlatform()
}
